# SPRINT 3


### EXERCICI 1

**Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.**

In [37]:
import numpy as np
import pandas as pd

array= np.arange(0,20,3)
array


array([ 0,  3,  6,  9, 12, 15, 18])

In [50]:
def func(array):
    if array.ndim==1:
        df=pd.DataFrame(array)
        print('El array es de una dimensión', df.describe())
    else:
        print('ERROR el array no cumple condición')
func(array)

El array es de una dimensión                0
count   7.000000
mean    9.000000
std     6.480741
min     0.000000
25%     4.500000
50%     9.000000
75%    13.500000
max    18.000000


### Exercici 2

**Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.**

In [40]:
from random import randint
def nueva_matriz(n):
    matriz = []
    for r in range (n):
        fila = []
        
        for c in range (n):
            fila.append(randint(1, 100))
        matriz.append(fila)
        
    return matriz

resultado= nueva_matriz (4)

print (resultado)

# se generó una matriz 4 x 4

[[23, 12, 18, 28], [48, 21, 6, 85], [19, 44, 82, 14], [3, 15, 33, 47]]


### Exercici 3 

**Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.**

In [42]:
import random
n = 4
m = 3

matriz = []
for i in range(n):
    matriz.append([]) #append para definir la matriz y asignarle sus valores
    for j in range(m):
        matriz[i].append(random.randint(0, 100))

sumaFila=[sum(i) for i in matriz]
sumaColumna=[sum(i) for i in zip(*matriz)]#toma 1 o 2 obj iterables y retorna uno nuevo


print('La matriz es: ', matriz)
print('La suma de las filas es: ', sumaFila)
print('La suma de la columna es: ', sumaColumna)

La matriz es:  [[91, 91, 64], [62, 39, 61], [19, 73, 74], [19, 22, 83]]
La suma de las filas es:  [246, 162, 166, 124]
La suma de la columna es:  [191, 225, 282]


In [43]:
#otra forma de crear matriz mxn
a=[[i for i in range(6)]for j in range(4)]
a

[[0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5]]

In [45]:
#otra forma más sencilla de hacerlo con numpy
import numpy as np
a = np.arange(12).reshape(4,3)
print(a)
s = np.sum(a, axis=0)
print("La suma de columnas es: ", s)
s = np.sum(a, axis=1)
print("La suma de filas es: ", s)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
La suma de columnas es:  [18 22 26]
La suma de filas es:  [ 3 12 21 30]


### Exercici 4

**Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.**

In [46]:
edad=[10, 12, 14, 16, 18]
peso=[30, 40, 45, 50, 55]

np.corrcoef (edad, peso)

# hay una correlación lineal positiva, aumenta la edad aumenta el peso, 
#es mejor en el caso de la edad porque claramente los numeros son de 2 en 2

array([[1.        , 0.98639392],
       [0.98639392, 1.        ]])